CREATE TABLE "public"."feeds" (
    "feed_id" bigint generated by default AS IDENTITY NOT NULL PRIMARY KEY,
    "feed_title" text NOT NULL,
    "feed_url" text UNIQUE NOT NULL,
    "last_fetched" timestamp with time zone
);