CREATE TABLE "public"."articles" (
    "article_id" bigint generated by default AS IDENTITY NOT NULL PRIMARY KEY,
    "feed_id" bigint REFERENCES public.feeds(feed_id) ON DELETE CASCADE NOT NULL,
    "reference_url" text NOT NULL,
    "title" text NOT NULL,
    "description" text,
    "thumbnail_url" text,
    "published_at" timestamp with time zone
);
